# Default values for helm_deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

ingress:
  enabled: true
  hosts:
    - laa-fee-scheme-api-uat.apps.live.cloud-platform.service.justice.gov.uk
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: "laa-fee-scheme-api-ingress-laa-fee-scheme-api-uat-green"

resources:
  limits:
    cpu: 500m
    memory: 1.5Gi
  requests:
    cpu: 200m
    memory: 1Gi

sentry:
  enabled: true
  environment: uat
  dsn: https://3dba04b677b4b24e1cd3380e474f7b26@o345774.ingest.us.sentry.io/4509803102666752

root:
  logging:
    level: INFO

spring:
  logging:
    level: INFO

application:
  logging:
    level: DEBUG

prometheus:
  enabled: true
  dashboardUrl: https://grafana.live.cloud-platform.service.justice.gov.uk/d/laa-fee-scheme-api-uat-dashboard
  severity: laa-fee-scheme-api-uat
  zeroPodsInterval: 1m