# Default values for helm_deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

ingress:
  enabled: true
  domain: apps.live.cloud-platform.service.justice.gov.uk
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: "{{ .Release.Name }}-green"

resources:
  limits:
    cpu: 500m
    memory: 1.5Gi
  requests:
    cpu: 200m
    memory: 1Gi

sentry:
  enabled: false

root:
  logging:
    level: INFO

spring:
  logging:
    level: INFO

application:
  logging:
    level: DEBUG
