{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-dashboard
  namespace: {{ .Release.Namespace }}
  labels:
    grafana_dashboard: ""
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name | quote }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace | quote }}
data:
  {{ .Release.Name }}-dashboard.json:
  {{ include "laa-fee-scheme-api-grafana-dashboard-template" . | quote | indent 4 }}
{{- end }}
