name: PR build and test
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v6

      - name: Build and run tests
        uses: './.github/actions/build-and-test'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  snyk-vulnerability-scan:
    uses: ./.github/workflows/snyk-vulnerability-scans.yml
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      SLACK_PROD_WEBHOOK_URL: ${{ secrets.SLACK_PROD_WEBHOOK_URL }}

  zap-pr-scan:
    uses: ./.github/workflows/zap-security-scan.yml
    secrets:
      SLACK_PROD_WEBHOOK_URL: ${{ secrets.SLACK_PROD_WEBHOOK_URL }}

  check-for-preview-deploy:
    if: contains(github.event.pull_request.labels.*.name, 'preview-deploy')
    needs: [ build-test, snyk-vulnerability-scan, zap-pr-scan ]
    uses: ./.github/workflows/deploy-preview.yml
    with:
      pr_number: ${{ github.event.pull_request.number }}
    secrets: inherit