name: Snyk vulnerability scans
on:
  schedule:
    - cron: '0 8 * * MON'
  workflow_call:
    secrets:
      SNYK_TOKEN:
        required: true
  workflow_dispatch:

jobs:
  vulnerability-scan-app:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v6

      - name: Setup Snyk CLI
        uses: snyk/actions/setup@master

      - name: Run Snyk scan
        run: snyk test -d --all-projects --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ env.SNYK_TOKEN }}
        shell: bash

  vulnerability-scan-docker:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'corretto'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build app jar with gradle
        run: ./gradlew build

      - name: Build a Docker image
        run: docker build -t laa-fee-scheme-api:scan .

      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        with:
          image: laa-fee-scheme-api:scan
          args: --file=Dockerfile --severity-threshold=high