name: Snyk vulnerability scans
on:
  schedule:
    - cron: '0 8 * * MON'
  workflow_call:
    secrets:
      SNYK_TOKEN:
        required: true
      SLACK_PROD_WEBHOOK_URL:
        required: true
  workflow_dispatch:

jobs:
  vulnerability-scan-app:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v6

      - name: Run Snyk to check app for vulnerabilities
        uses: snyk/actions/gradle@master
        with:
          command: code test
          args: --severity-threshold=high

  vulnerability-scan-docker:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'corretto'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build app jar with gradle
        run: ./gradlew build

      - name: Build a Docker image
        run: docker build -t laa-fee-scheme-api:scan .

      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        with:
          image: laa-fee-scheme-api:scan
          args: --file=Dockerfile --severity-threshold=high

  notify-slack:
    needs:
      - vulnerability-scan-app
      - vulnerability-scan-docker
    if: always() &&
      github.event_name == 'schedule' &&
      github.ref == 'refs/heads/main' &&
      contains(join(needs.*.result, ' '), 'failure')
    uses: ./.github/workflows/notify-slack.yml
    with:
      scan_name: "Snyk vulnerability scan"
      message_details: |
        App scan: ${{ needs.vulnerability-scan-app.result }}
        Docker scan: ${{ needs.vulnerability-scan-docker.result }}
    secrets:
      SLACK_PROD_WEBHOOK_URL: ${{ secrets.SLACK_PROD_WEBHOOK_URL }}